sudo: required

services:
  - docker

before_install:
  - docker build -t test-web-image -f Dockerfile.dev .

script:
  - docker run -e CI=true test-web-image npm run test

# aws deployment config
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "k8s-project"
  env: "K8sProject-env"
  bucket_name: "elasticbeanstalk-us-east-2-870553296052"
  bucket_path: "k8s-project"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
